
start: main.cpp C:\Users\Akash\Documents\Libraries\glad\src\glad.c
	cl /MD main.cpp C:\Users\Akash\Documents\Libraries\glad\src\glad.c /IC:\Users\Akash\Documents\Programming\OpenGL\Include /IC:\Users\Akash\Documents\Libraries\glfw3\include /IC:\Users\Akash\Documents\Libraries\glad\include /IC:\Users\Akash\Documents\Libraries\freetype\include /IC:\Users\Akash\Documents\Libraries /link /LIBPATH:"C:\Users\Akash\Documents\Libraries\glfw3\lib-vc2015" /LIBPATH:"C:\Users\Akash\Documents\Libraries\freetype\lib" glfw3.lib freetype.lib gdi32.lib user32.lib shell32.lib
